---
sudo: false
language: scala
scala:
  - 2.12.x
  - 2.13.x
  - 3.x

env:
  - TRAVIS_JDK=11
  - TRAVIS_JDK=17

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

script: sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba/jdk"
    - "$HOME/.sbt"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/72d2a40c7c3ae2988d66
    on_success: always
    on_failure: always
    on_start: always
